### ISSUE TITLE
Unable to convert behind a corporate proxy

### ISSUE THREAD

**Issue by GuillaumedesPommareSAP** [LucyBot-Inc/api-spec-converter#137]
Hello !

api-spec-converter is working as long as I am converting a resource connected to a public network without proxy. I am trying to convert a raml into a swagger 2.0 file.
When I am at work, behind a corporate proxy, I can't have it working properly. Always getting some "connect ETIMEDOUT" errors.

I have to say that my proxy environment variables are set (for http and https) and the https.get is working behind the proxy as soon as I use a https-proxy-agent to do this get.

Looking into the code, the libraries used, and even the requirements from the libraries (raml-parser) I am not so sure proxies are supported at all.

Could you confirm this impression ? if yes, would it make sense to add proxy support to this tool ?

Thanks,
Guillaume

**Comment by bobby-brennan** [comment]
Hi Guillaume,

I'm not sure what might be going wrong here. I don't think api-spec-converter or raml-parser do anything too out of the ordinary when requesting resources over HTTP, and we don't have any proxy-specific code in there. So as long as your proxy is configured correctly, I think everything should work.

If you're able to alter the code to fix the proxy issue, let me know and we can try and merge it in. 

You could also try downloading all the resources manually, and changing the $refs to point to the local files instead of URLs, or setting up a local HTTP server for the RAML files and altering your hosts file to point to localhost.

Hope that helps, let me know if you get anywhere or have further questions.

-Bobby
