### ISSUE TITLE
Running Synchronous

### ISSUE THREAD

**Issue by codr1** [LucyBot-Inc/api-spec-converter#144]
This is more of a question - can I run your functions synchronously?

Also - can I pass an object instead of a file name?   (The use case here is that I just parsed in a file and figured out it is say Swagger 1.2.  I now want to convert it to 2.0, but I don't really want to read it in again).

**Comment by codr1** [comment]
...I am trying to convert all the files in a directory.  I need to either run it for each file synchronously or somehow pass in extra data such as the output file name.

**Comment by bobby-brennan** [comment]
You have a couple options for running this inside a loop:

1. You can use async/await syntax (requires Node v8):

```js
(async function() {
  for (let key in items) {
    let converted = await Converter.convert({});
  }
})();
```

2. You can use the [async library](https://caolan.github.io/async/) to run the conversions in series or in parallel (`async.series` or `async.parallel`)

For your second question, you do need to pass it a file or URL. The converter needs access to the underlying file because there are sometimes details that don't make it into the parsed object, e.g. in API Blueprint.
